import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'is-object': 'src/is-object.ts',
    'is-object-of': 'src/is-object-of.ts',
    'is-non-null-object': 'src/is-non-null-object.ts',
    'is-record': 'src/is-record.ts',
    'is-null': 'src/is-null.ts',
    'is-undefined': 'src/is-undefined.ts',
    'is-union-of': 'src/is-union-of.ts',
    'is-string': 'src/is-string.ts',
    'is-number': 'src/is-number.ts',
    'is-finite-number': 'src/is-finite-number.ts',
    'is-integer': 'src/is-integer.ts',
    'is-boolean': 'src/is-boolean.ts',
    'is-function': 'src/is-function.ts',
    'has-key': 'src/has-key.ts',
    'is-array': 'src/is-array.ts',
    'is-array-of': 'src/is-array-of.ts',
    'is-non-empty-array': 'src/is-non-empty-array.ts',
    'is-empty-array': 'src/is-empty-array.ts',
    'is-in-array': 'src/is-in-array.ts',
    'is-one-of': 'src/is-one-of.ts',
    'is-tuple': 'src/is-tuple.ts',
    assert: 'src/assert.ts',
    'assert-defined': 'src/assert-defined.ts',
    brand: 'src/brand.ts',
    'is-api-error-response': 'src/is-api-error-response.ts',
    parse: 'src/parse.ts',
  },
  format: ['cjs', 'esm'],
  dts: false,
  sourcemap: false,
  clean: true,
  treeshake: true,
  minify: false,
});
